"""empty message

Revision ID: 343caa227373
Revises: 
Create Date: 2018-12-28 20:44:13.945235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343caa227373'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clas', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'clas')
    # ### end Alembic commands ###
